language: go
go:
 - 1.8

install:
  - go get -t ./...
  - go get github.com/stretchr/testify/assert  # This doesn't pick up the testing dependency as they are tagged (int and end to end)

script:
 - go build .
 - go test -v -tags=endtoend -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
