language: go
go:
 - 1.6

install:
  - go get -t ./...

script:
 - go build
 - go get golang.org/x/tools/cmd/vet
 - go vet
 - go test -v -tags=integration           # Run integration tests + unit tests
 - go test -v -tags=endtoend           # Run integration tests + unit tests
 - cd cmd
 - cd repoclone
 - go build